### ISSUE TITLE
Profile cannot be loaded

### ISSUE THREAD

**Issue by nahuelange** [andreasgal/B2G#200]
Hi,

I tryied to test boot2gecko using the emulator mode, that compile correctly. But when I launch it, I have this error:
Your B2G profile cannot be loaded. It may be missing or inaccessible.

Have you and idea where i'm wrong? or is it a bug?

thanks.

**Comment by nahuelange** [comment]
Launching manually adb made it working. It should be added to the install doc.

**Comment by lquterqtd** [comment]
I met the same trouble.Could you please tell me how to do that in details?

**Comment by lquterqtd** [comment]
I have known how to do with that.
when i first type: ./emu.sh
there is a warning: 
emulator: WARNING: data partition size adjusted to match image file (83 MB > 66 MB)
then:
disk.systemPartition.size = 66m
disk.dataPartition.size = 83m

so Your B2G profile cannot be loaded. It may be missing or inaccessible.

maybe it's because the systemPartition size is less than dataPartition size

and i add the following line to emu.sh:

-partition-size 512

do not add it to the end.

and it worked.
