### ISSUE TITLE
Timeout causes phone to go blank - requiring hard reboot

### ISSUE THREAD

**Issue by jammink** [andreasgal/B2G#267]
gaia commit b4388a51df62b79f161536cf56cea980e97d75ae
b2g commit fd32ad8833e43dcc91f5541417938ee65ed37bf7

Samsung Galaxy SGS2
Nexus S

After approx: 55 seconds, the phones go blank, and apparently die.  It is only possible to restart the phone by taking the battery out, replacing, and restarting with power.

**Comment by jammink** [comment]
Reproduced on Nexus S for the latest ICS build.

Logcat here: http://pastebin.mozilla.org/1563259

**Comment by jeffgca** [comment]
This happens for me, 'classic' sgs2 build, no way to wake the device from sleep leading to a battery pull.

**Comment by robhawkes** [comment]
I've been experiencing this for a few days now on an S2 device.

**Comment by jeffgca** [comment]
More detail: 

I hooked up the phone to my computer with logcat running and let it time out. Adb continues running and I can see log message produced by the phone when I hit volume up/down, but no event happens when I press the power or home buttons. If I press the power button for a very very long time, the phone re-boots and adb quits.

**Comment by robhawkes** [comment]
To clarify… like @canuckistani, I can still access the device through ADB when it's 'dead' but none of the hardware buttons do anything unless I reboot the device (either through ADB, removal of battery, or a long press on the power button).

**Comment by atilag** [comment]
I'm not sure if I've had the same problem on my SGS2 some weeks ago. But the behaivor was the same that you are describing.
It seemed like "b2g" process stops responding, I can made it work again by killing the process from adb shell: "killall b2g",  and restarts it: "/system/b2g/b2g"
I fixed this issue by updating Gaia... (I suppouse you already did, this is cause I'm not sure if this bug is the same I got)

**Comment by jeffgca** [comment]
I pulled from master this morning and updated gaia - it seems to be working fine now. Rob: you should try doing the same?

**Comment by robhawkes** [comment]
Just pulled the latest Gaia and pushed it to the phone. The lock/blank screen bug seems to be gone now.

**Comment by jammink** [comment]
I have seen the same problem - and have seen it go away also.  What seems to be happening is that the button handlers are part of gaia - when these aren't there - pushing the buttons has no effect, and so the screen goes blank, never to be resurrected.  Closing - but noting to self that this is a regression case, because I have seen this come and go.

**Comment by jeffgca** [comment]
I think what is also happening is that gaia is doing soem sort of 'update' to a previous version after I update it.

Here's what I did:
- added a new default wallpaper to gaia ( http://is.gd/HOZBME ) 
- updated gaia on my phone
- time passes, seems to work, and I get and dismiss an update notification for the 'settings' app
- time passes, and I notice that my wallpaper is missing from settings
- restore from sleep by pushing the button no longer works

Does this make sense? It's kind of annoying if the update service squashes my local changes after I've been hacking. How do I turn off updates?

**Comment by huwge** [comment]
Hi,

I am using git commit 0ef4c72ec498f96c047e98135e87400b1c150bbd of gaia and I am being bitten by this problem.
The device seems to be dead, adb can still talk to it and killing b2g in the adb shell gets me working again.
