### ISSUE TITLE
update the fork of mozilla-central

### ISSUE THREAD

**Issue by fabricedesre** [andreasgal/B2G#31]
The fork of m-c should be updated on a regular basis (daily?).

**Comment by joneschrisg** [comment]
While we're maintaining a nontrivial fork (the b2g/htmlrunner/etc. XUL stuff) that's not in upstream m-c, I would prefer to pull less often, so that we don't have to deal with breakage.  Once we've upstreamed that XUL code, and b2g has automated tests etc., I would be very happy to pull daily.

For this update, is there a particular changeset you want me to pull?
