### ISSUE TITLE
Add the identi.ca group to the README.md

### ISSUE THREAD

**Issue by aurium** [andreasgal/B2G#5]
That is the address: http://identi.ca/group/boot2gecko

**Comment by joneschrisg** [comment]
What missing piece would this new group fill in the existing github, wiki, newsgroup/mailing list, twitter account, and IRC channel?  Not trying to discourage you, but we've learned the hard way at Mozilla that having too many communication channels is harmful, not helpful, since people don't know which to follow or where to go with questions and comments.

**Comment by aurium** [comment]
StatusNet group is a efficient news and ideas multicast place.
It is not dense like mailing lists or volatile like irc.

If you know the StatusNet service, you know that you can unify a SN account with a Twitter account.

Unify identi.ca/boot2gecko + identi.ca/group/boot2gecko + twitter.com/Boot2Gecko is to use only one message media to touch more people and give the needed interaction options to all. That will not be more work.

This 3 options will have the same information, if you do it right. The public will not lost Mozilla messages and all user messages will find the Mozilla. Does not matter if the user don't know it, his comments will be read.
- Twitter account: for the speak only persons.
- Identi.ca account: for who prioritize FOSS and have the attitude to use.
- Identi.ca group: for who want to talk about with other interested persons.

Well, truly, if you need my explanation that means you don't care enough about FOSS. The most important people to help the B2G start is the FOSS serious users and developers, and they like identi.ca, a service based on FOSS, different of the Twitter. That is clear when we see that you prefer to create the repository here and not on Gitorious.

Well, i did for you. I think the serious FOSS community must be your priority ever. Or sorry if i misunderstand the Mozilla objectives.

**Comment by joneschrisg** [comment]
You didn't list anything concrete this would add on top of the existing media.  Like I said above, more media for the sake of more media is harmful rather than helpful.  More power to you in continuing the identi.ca group; convince us why it would help.

The bizarre accusations in the latter part of your comment don't help anyone, especially yourself.
